= Counter with trigger output in SystemVerilog
MIURA Katsuyoshi <miura.katsuyoshi@gmail.com>
v1.0, 2021-04-10
:toc:
:xrefstyle: short
:imagesdir: Images
:homepage: https://github.com/miura-katsuyoshi/LFSR

Parameterized counter with single-cycle trigger output in SystemVerilog.

This is a simple binary counter implemented in SystemVerilog.  The bit width of the counter can be spefified by the parameter _WIDTH_.  It has trigger outputs _trig_out_.  The output _trig_out[i]_ becomes 1 when _count[i]_ goes to 0 from 1.  The pulse width of _trig_out[i]_ is single cycle even if counting up is disabled by deasserting _n_en_ during _trig_out[i]_=1.

== Input/Output

[cols="1,1,1,1,1,3"]
|===
|Name |Direction |Width |Polarity |Initial value |Description

|clk | input | 1 |- |- |Clock
|n_rst | input |1 |negative |- |Reset
|n_en |input |1 |negative |- |Enable counting up
|count |output |WIDTH |- |0 |count value
|trig_out |output |WIDTH |positive |0 |Trigger output.  This output becomes 1 during only one cycle when _count[i]_ becomes to 0 from 1.
|===

== Parameter

[cols="1,1,1,1,3"]
|===
|Name |Type |Width |Default value |Description

|WIDTH | int | 32 |8 |The bit width of _count_ and _trig_out_.
|===

== Timing-chart

A timing-chart of 3-bit counter is shown in <<fig:timing_chart>>.

[[fig:timing_chart]]
.A timing-chart of 3-bit counter.
image::timing_chart.svg[]

== Instantiation

    counter #(
        .WIDTH(8
    )
    counter_u0(
        .clk(clk_signal),
        .n_rst(n_rst_signal),
        .n_en(n_en_signal),
        .count(counter_wire),
        .trig_out(trig_out_wire)
    );

== Test

A testbench based on https://vunit.github.io/[VUnit] is included in this repository.  Execute the script _run.py_ with python interpreter.  How to run the script is depending on your system.

 $ ./run.py
 $ python run.py
 $ python3 run.py
 $ py run.py
